//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerroApp
{
    public partial class Carrito
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.GridView gvCarrito;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.Button btnVaciar;
        protected global::System.Web.UI.WebControls.Button btnPagar;
        protected global::System.Web.UI.WebControls.HyperLink lnkSeguir;
    }
}
