//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerroApp
{
    public partial class Ticket
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.Label lblFecha;
        protected global::System.Web.UI.WebControls.Label lblNumeroCompra;
        protected global::System.Web.UI.WebControls.Label lblUsuario;
        protected global::System.Web.UI.WebControls.GridView gvTicket;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.Button btnGenerar;
        protected global::System.Web.UI.WebControls.HyperLink lnkVolver;
    }
}
